"""add_food_profile

Revision ID: 974374726f59
Revises: 1f4c8072c12f
Create Date: 2026-05-15 18:18:38.666767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '974374726f59'
down_revision: Union[str, Sequence[str], None] = '1f4c8072c12f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_profile',
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('dish_role', sa.String(length=20), nullable=True),
    sa.Column('food_group', sa.String(length=20), nullable=True),
    sa.Column('gi', sa.Integer(), nullable=True),
    sa.Column('gl', sa.Float(), nullable=True),
    sa.Column('purine_mg', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.PrimaryKeyConstraint('food_id')
    )
    op.create_table('user_food_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guest_id', sa.String(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('feedback_type', sa.String(), nullable=False, comment='like/dislike/saved/ignored'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_food_feedback_guest_id'), 'user_food_feedback', ['guest_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_food_feedback_guest_id'), table_name='user_food_feedback')
    op.drop_table('user_food_feedback')
    op.drop_table('food_profile')
    # ### end Alembic commands ###
