-- sql/schema.sql

CREATE EXTENSION IF NOT EXISTS vector;

-- vision_foods를 먼저 생성한다.
-- image_embeddings.food_id 가 vision_foods.food_id 를 참조하기 때문이다.
CREATE TABLE IF NOT EXISTS vision_foods (
    food_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_name_raw TEXT NOT NULL,
    food_name_norm TEXT NOT NULL,
    serving_basis DOUBLE PRECISION,
    calories_kcal DOUBLE PRECISION,
    protein_g DOUBLE PRECISION,
    fat_g DOUBLE PRECISION,
    carbs_g DOUBLE PRECISION,
    sugars_g DOUBLE PRECISION,
    fiber_g DOUBLE PRECISION,
    sodium_mg DOUBLE PRECISION,
    potassium_mg DOUBLE PRECISION,
    cholesterol_mg DOUBLE PRECISION,
    sat_fat_g DOUBLE PRECISION,
    caffeine_mg DOUBLE PRECISION,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT vision_foods_food_name_norm_uk
        UNIQUE (food_name_norm),

    CONSTRAINT vision_foods_food_name_norm_ck
        CHECK (btrim(food_name_norm) <> '')
);

CREATE TABLE IF NOT EXISTS image_embeddings (
    image_id BIGINT PRIMARY KEY,
    rename_id BIGINT NOT NULL UNIQUE,
    class_seq INTEGER NOT NULL,

    -- vision_foods 와의 FK: load_embeddings.py 실행 전에 load_foods.py 가 완료되어야 한다.
    -- 이 FK 덕분에 vision_foods 에 없는 class 는 적재 자체가 불가능하다.
    food_id BIGINT NOT NULL REFERENCES vision_foods(food_id),

    class_name_raw TEXT NOT NULL,
    class_name_norm TEXT NOT NULL,
    relative_path TEXT NOT NULL,
    original_relative_path TEXT NOT NULL,
    model_name TEXT NOT NULL,
    -- embedding_dim 컬럼 제거: vector(768) 타입이 차원을 이미 강제하므로 중복
    embedding vector(768) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT image_embeddings_class_name_norm_ck
        CHECK (btrim(class_name_norm) <> '')
);

CREATE INDEX IF NOT EXISTS idx_image_embeddings_class_seq
    ON image_embeddings (class_seq);

CREATE INDEX IF NOT EXISTS idx_image_embeddings_model_name
    ON image_embeddings (model_name);

CREATE INDEX IF NOT EXISTS idx_image_embeddings_food_id
    ON image_embeddings (food_id);

-- =========================================================
-- IMPORTANT:
-- 아래 벡터 인덱스는 대량 적재(load_embeddings.py) 이후에 생성하는 것을 권장
-- 지금 바로 실행해도 되지만, 초기 적재 속도는 느려질 수 있음
-- 적재 완료 후 아래 구문만 따로 실행하면 됨
-- =========================================================
--
-- CREATE INDEX IF NOT EXISTS idx_image_embeddings_embedding_hnsw_cosine
--     ON image_embeddings
--     USING hnsw (embedding vector_cosine_ops);
